import AdminWorkspace from "../shared/AdminWorkspace";
import { eventScoutTab } from "../scout/scoutLaneTabs";

const communityTabs = [
  eventScoutTab,
  {
    id: "applications",
    label: "Event Applications",
    table: "event_applications",
    primary: "applicant_name",
    secondary: "application_type",
    status: "status",
    help: "Vendors, artists, practitioners, sponsors, volunteers, and community leads.",
    description: "Add or review people who may participate in a HEHA event. This does not approve them publicly.",
    initial: { applicant_name: "", brand_or_business_name: "", application_type: "vendor", email: "", phone: "", instagram: "", website: "", category: "", event_interest: "", proposed_contribution: "", notes: "", status: "new" },
    fields: [
      { name: "applicant_name", label: "Applicant name", required: true },
      { name: "brand_or_business_name", label: "Brand / business" },
      { name: "application_type", label: "Application type", type: "select", options: ["vendor", "artist", "wellness_practitioner", "sponsor", "volunteer", "community_ambassador", "venue_host"] },
      { name: "email", label: "Email" },
      { name: "phone", label: "Phone" },
      { name: "instagram", label: "Instagram" },
      { name: "website", label: "Website" },
      { name: "category", label: "Category" },
      { name: "event_interest", label: "Event interest", type: "textarea" },
      { name: "proposed_contribution", label: "Possible contribution", type: "textarea" },
      { name: "notes", label: "Internal notes", type: "textarea" },
    ],
  },
  {
    id: "concepts",
    label: "Event Concepts",
    table: "event_concepts",
    primary: "title",
    secondary: "event_type",
    status: "status",
    help: "Draft ideas before anything becomes a public promise.",
    description: "Create event drafts and keep them in draft/review status until Geronimo approves.",
    initial: { title: "", event_type: "soft_launch_mixer", event_goal: "", target_audience: "", theme_or_vibe: "", proposed_location: "", proposed_date_window: "", estimated_size: "", possible_partners: "", budget_needed: "", sponsor_potential: "", risks: "", questions: "", status: "draft" },
    fields: [
      { name: "title", label: "Concept title", required: true },
      { name: "event_type", label: "Event type", type: "select", options: ["soft_launch_mixer", "wellness_popup", "healthy_food_tasting", "vendor_market", "artist_community_night", "launch_party", "sponsor_event"] },
      { name: "event_goal", label: "Goal" },
      { name: "target_audience", label: "Target audience" },
      { name: "theme_or_vibe", label: "Theme / vibe" },
      { name: "proposed_location", label: "Proposed location" },
      { name: "proposed_date_window", label: "Proposed date window" },
      { name: "estimated_size", label: "Estimated size" },
      { name: "possible_partners", label: "Possible partners", type: "textarea" },
      { name: "budget_needed", label: "Budget needed" },
      { name: "sponsor_potential", label: "Sponsor potential" },
      { name: "risks", label: "Risks", type: "textarea" },
      { name: "questions", label: "Questions for Geronimo", type: "textarea" },
    ],
  },
  {
    id: "invites",
    label: "Invite List",
    table: "invite_list",
    primary: "name",
    secondary: "category",
    status: "invite_status",
    help: "Warm launch/event invitation and RSVP tracking.",
    initial: { name: "", contact_method: "instagram", email: "", phone: "", instagram: "", category: "", neighborhood: "", relationship_strength: "warm", invite_status: "not_contacted", rsvp_status: "unknown", follow_up_date: "", notes: "" },
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "contact_method", label: "Contact method", type: "select", options: ["instagram", "email", "phone", "in_person", "other"] },
      { name: "instagram", label: "Instagram" },
      { name: "email", label: "Email" },
      { name: "phone", label: "Phone" },
      { name: "category", label: "Category" },
      { name: "neighborhood", label: "Neighborhood" },
      { name: "relationship_strength", label: "Relationship", type: "select", options: ["cold", "warm", "strong", "partner", "friend"] },
      { name: "follow_up_date", label: "Follow-up date", type: "date" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    id: "outreach",
    label: "Community Outreach",
    table: "community_outreach",
    primary: "lead_name",
    secondary: "interest_area",
    status: "status",
    help: "DMs, event leads, sponsors, venues, artists, vendors, and follow-ups.",
    initial: { lead_name: "", lead_type: "community_lead", source: "", contact_info: "", interest_area: "", conversation_notes: "", next_step: "", follow_up_date: "", status: "new_lead" },
    fields: [
      { name: "lead_name", label: "Lead name", required: true },
      { name: "lead_type", label: "Lead type" },
      { name: "source", label: "Source" },
      { name: "contact_info", label: "Contact info" },
      { name: "interest_area", label: "Interest area" },
      { name: "next_step", label: "Next step" },
      { name: "follow_up_date", label: "Follow-up date", type: "date" },
      { name: "conversation_notes", label: "Conversation notes", type: "textarea" },
    ],
  },
  {
    id: "content",
    label: "Content Requests",
    table: "admin_content_requests",
    filter: { type: "eq", column: "dashboard_area", value: "community_events" },
    defaults: { dashboard_area: "community_events", approval_needed: true, status: "requested" },
    primary: "request_title",
    secondary: "request_type",
    status: "status",
    help: "Flyers, captions, Swipe cards, website sections, and recap requests.",
    initial: { request_title: "", request_type: "event_flyer", priority: "medium", needed_by: "", audience: "", key_message: "", assets_link: "", canva_link: "", notes: "" },
    fields: [
      { name: "request_title", label: "Request title", required: true },
      { name: "request_type", label: "Request type", type: "select", options: ["event_flyer", "event_caption", "swipe_card", "website_event_section", "newsletter_feature", "artist_vendor_spotlight", "sponsor_post", "event_recap_post"] },
      { name: "priority", label: "Priority", type: "select", options: ["low", "medium", "high", "critical"] },
      { name: "needed_by", label: "Needed by", type: "date" },
      { name: "audience", label: "Audience" },
      { name: "assets_link", label: "Assets link" },
      { name: "canva_link", label: "Canva link" },
      { name: "key_message", label: "Key message", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    id: "approvals",
    label: "Geronimo Approvals",
    table: "admin_approval_requests",
    filter: { type: "eq", column: "dashboard_area", value: "community_events" },
    defaults: { dashboard_area: "community_events", related_type: "event", status: "needs_geronimo_review" },
    primary: "approval_type",
    secondary: "approval_reason",
    status: "status",
    help: "Final decisions that must go to Geronimo.",
    initial: { approval_type: "event_concept_approval", approval_reason: "", risk_level: "medium" },
    fields: [
      { name: "approval_type", label: "Approval type", type: "select", options: ["event_concept_approval", "public_event_page_approval", "vendor_participation_approval", "sponsor_approval", "invite_wording_approval", "final_date_approval", "payment_compensation_approval", "public_promotion_approval"] },
      { name: "risk_level", label: "Risk level", type: "select", options: ["low", "medium", "high", "critical"] },
      { name: "approval_reason", label: "Why approval is needed", type: "textarea" },
    ],
  },
  {
    id: "recaps",
    label: "Event Recaps",
    table: "event_recaps",
    primary: "event_name",
    secondary: "location",
    status: "event_date",
    help: "After-event notes, signups, leads, lessons, and next steps.",
    initial: { event_name: "", event_date: "", location: "", estimated_attendance: "", partners_involved: "", new_leads_collected: "", app_signups: "", photos_videos_link: "", what_worked: "", what_did_not_work: "", follow_up_needed: "", next_event_recommendation: "" },
    fields: [
      { name: "event_name", label: "Event name", required: true },
      { name: "event_date", label: "Event date", type: "date" },
      { name: "location", label: "Location" },
      { name: "estimated_attendance", label: "Attendance estimate", type: "number" },
      { name: "partners_involved", label: "Partners involved" },
      { name: "new_leads_collected", label: "New leads", type: "number" },
      { name: "app_signups", label: "App signups", type: "number" },
      { name: "photos_videos_link", label: "Photo/video link" },
      { name: "what_worked", label: "What worked", type: "textarea" },
      { name: "what_did_not_work", label: "What did not work", type: "textarea" },
      { name: "follow_up_needed", label: "Follow-up needed", type: "textarea" },
      { name: "next_event_recommendation", label: "Next event recommendation", type: "textarea" },
    ],
  },
];

export default function CommunityDashboard({ final }) {
  return <AdminWorkspace lane="Community / Events" title="Niña Community Activation Dashboard" subtitle="A protected internal workspace for scout and venue leads, event applications, concepts, invite lists, outreach, content requests, approval requests, and recaps. Niña organizes momentum; Geronimo approves final public commitments." final={final} tabs={communityTabs} overview={[{ eyebrow: "Boundary", title: "Organize first. Approve later.", body: "This dashboard creates internal structure. It is not a public event marketplace and does not publish anything automatically." }]} />;
}
