export const ROLE_LABELS = {
  super_admin: "Geronimo / Super Admin",
  pm_admin: "Myren / PM Admin",
};

export const ALLOWED_INTERNAL_ROLES = ["super_admin", "pm_admin"];
export const PM_ACCESS_ROLES = ["super_admin", "pm_admin"];

export const OVERVIEW_CARD_DEFS = [
  {
    key: "active_partner_profiles",
    label: "Active partner profiles",
    table: "admin_partner_readiness",
    filterType: "notIn",
    col: "pipeline_status",
    vals: ["paused", "rejected", "archived"],
    note: "Partners moving through onboarding, listing, or certification.",
  },
  {
    key: "new_submissions",
    label: "New submissions",
    table: "admin_partner_readiness",
    filterType: "in",
    col: "pipeline_status",
    vals: ["new_lead", "application_started", "profile_draft"],
    note: "New leads, applications, and draft profiles waiting on review.",
  },
  {
    key: "profiles_missing_info",
    label: "Profiles missing info",
    table: "admin_partner_readiness",
    filterType: "in",
    col: "profile_status",
    vals: ["missing_required_info", "missing_assets", "needs_content_review"],
    note: "Profiles blocked by missing info, assets, or content review.",
  },
  {
    key: "missing_assets",
    label: "Missing assets",
    table: "admin_missing_items",
    filterType: "in",
    col: "status",
    vals: ["open", "assigned", "waiting_on_business", "waiting_on_content_team"],
    note: "Open missing-info and asset follow-ups.",
  },
  {
    key: "deal_requests",
    label: "Deal requests",
    table: "admin_deal_requests",
    filterType: "in",
    col: "final_status",
    vals: ["draft", "info_needed", "content_needed", "ready_for_geronimo_review", "changes_requested"],
    note: "Community Pass, Swoop, SuperSwoop, and local discount items.",
  },
  {
    key: "certification_reviews",
    label: "Certification reviews",
    table: "admin_certification_reviews",
    filterType: "in",
    col: "certification_status",
    vals: ["requested", "missing_info", "in_review", "needs_geronimo_decision"],
    note: "Track only. Geronimo approves badges.",
  },
  {
    key: "visibility_issues",
    label: "Visibility issues",
    table: "admin_platform_visibility",
    filterType: "visibilityOr",
    orClause: [
      "heha_swipe_status.eq.needs_update",
      "heha_swipe_status.eq.error_broken_link",
      "heha_local_status.eq.needs_update",
      "heha_local_status.eq.error_broken_link",
      "wix_status.eq.needs_update",
      "wix_status.eq.error_broken_link",
      "hubspot_status.eq.needs_update",
      "hubspot_status.eq.error_broken_link",
    ].join(","),
    note: "Wix, HEHA Local, HEHA Swipe, or HubSpot mismatches.",
  },
  {
    key: "needs_geronimo_approval",
    label: "Needs Geronimo approval",
    table: "admin_approval_requests",
    filterType: "eq",
    col: "status",
    val: "needs_geronimo_review",
    note: "Risky or final-decision items waiting on Geronimo.",
  },
  {
    key: "hubspot_sync_issues",
    label: "HubSpot sync issues",
    table: "admin_hubspot_links",
    filterType: "in",
    col: "sync_status",
    vals: ["failed", "needs_review"],
    note: "Backend or Make sync status. No frontend token.",
  },
  {
    key: "weekly_report_drafts",
    label: "Weekly report drafts",
    table: "admin_weekly_reports",
    filterType: "in",
    col: "report_status",
    vals: ["draft", "ready_for_review"],
    note: "Reports not yet sent or archived.",
  },
];

export const DASHBOARD_TABS = [
  { id: "overview", label: "Overview" },
  { id: "partners", label: "Partners" },
  { id: "missing", label: "Missing Info" },
  { id: "deals", label: "Deals" },
  { id: "certification", label: "Certification" },
  { id: "visibility", label: "Visibility" },
  { id: "content", label: "Content" },
  { id: "approvals", label: "Approvals" },
  { id: "tasks", label: "Tasks" },
  { id: "reports", label: "Reports" },
];

export const TABLES = {
  partners: {
    title: "Partner Pipeline",
    table: "admin_partner_readiness",
    order: "updated_at",
    columns: ["business_name", "partner_category", "pipeline_status", "profile_status", "next_step", "blocker", "due_date", "approval_needed"],
    editable: ["pipeline_status", "profile_status", "next_step", "blocker", "due_date", "approval_needed", "internal_notes"],
  },
  missing: {
    title: "Missing Info + Asset Tracker",
    table: "admin_missing_items",
    order: "updated_at",
    columns: ["missing_item_type", "status", "due_date", "follow_up_method", "escalation_needed", "notes"],
    editable: ["status", "due_date", "follow_up_method", "escalation_needed", "notes"],
  },
  deals: {
    title: "Deals / Discounts Queue",
    table: "admin_deal_requests",
    order: "updated_at",
    columns: ["deal_title", "deal_type", "proposed_discount", "final_status", "approval_status", "start_date", "end_date"],
    editable: ["proposed_discount", "deal_terms", "redemption_method", "start_date", "end_date", "content_needed", "final_status", "risk_notes"],
  },
  certification: {
    title: "Listed But Not Certified Tracker",
    table: "admin_certification_reviews",
    order: "updated_at",
    columns: ["certification_status", "badge_status", "missing_items", "risk_notes", "geronimo_decision", "reviewed_at"],
    editable: ["certification_status", "missing_items", "risk_notes", "badge_status"],
  },
  visibility: {
    title: "Platform Visibility Tracker",
    table: "admin_platform_visibility",
    order: "updated_at",
    columns: ["heha_swipe_status", "heha_local_status", "wix_status", "hubspot_status", "mismatch_notes", "last_checked_at"],
    editable: ["heha_swipe_status", "heha_local_status", "wix_status", "hubspot_status", "mismatch_notes", "heha_swipe_url", "heha_local_url", "wix_url"],
  },
  content: {
    title: "Content Request Module",
    table: "admin_content_requests",
    order: "updated_at",
    columns: ["request_type", "priority", "status", "needed_by", "key_message", "approval_needed"],
    editable: ["priority", "status", "needed_by", "key_message", "assets_provided", "canva_link", "approval_needed", "notes"],
  },
  approvals: {
    title: "Geronimo Approval Queue",
    table: "admin_approval_requests",
    order: "updated_at",
    columns: ["approval_type", "status", "risk_level", "approval_reason", "geronimo_decision", "decision_notes"],
    editable: ["status", "risk_level", "approval_reason", "geronimo_decision", "decision_notes"],
  },
  tasks: {
    title: "Team Task + Blocker Tracker",
    table: "admin_pm_tasks",
    order: "updated_at",
    columns: ["task_title", "category", "priority", "status", "due_date", "blocker", "next_step", "approval_needed"],
    editable: ["category", "priority", "status", "due_date", "blocker", "next_step", "approval_needed", "notes"],
  },
  reports: {
    title: "Weekly Report Generator",
    table: "admin_weekly_reports",
    order: "report_week",
    columns: ["report_week", "report_status", "what_moved_forward", "blockers", "geronimo_approval_needed", "next_week_focus"],
    editable: ["report_status", "what_moved_forward", "blockers", "geronimo_approval_needed", "closest_to_live", "next_week_focus"],
  },
};

export const STATUS_OPTIONS = {
  pipeline_status: ["new_lead", "contacted", "interested", "application_started", "profile_draft", "missing_info", "content_needed", "ready_for_geronimo_review", "approved_to_list", "listed_not_certified", "certification_review_pending", "certified_verified", "paused", "rejected", "archived"],
  profile_status: ["draft", "missing_required_info", "missing_assets", "needs_content_review", "ready_for_geronimo_review", "approved", "live", "paused", "needs_update"],
  status: ["draft", "needs_geronimo_review", "approved", "changes_requested", "rejected", "paused", "open", "assigned", "waiting_on_business", "waiting_on_content_team", "waiting_on_geronimo", "received", "completed", "todo", "in_progress", "waiting", "blocked", "needs_approval", "archived", "requested", "ready_for_review", "published"],
  final_status: ["draft", "info_needed", "content_needed", "ready_for_geronimo_review", "approved", "changes_requested", "scheduled", "live", "paused", "rejected", "expired"],
  approval_status: ["draft", "needs_geronimo_review", "approved", "changes_requested", "rejected", "paused"],
  certification_status: ["not_requested", "requested", "missing_info", "in_review", "needs_geronimo_decision", "approved", "rejected", "paused", "recheck_later"],
  badge_status: ["none", "listed_only", "pending", "approved", "rejected", "paused"],
  sync_status: ["not_synced", "success", "failed", "needs_review", "paused"],
  report_status: ["draft", "ready_for_review", "sent", "archived"],
  priority: ["low", "medium", "high", "critical"],
  risk_level: ["low", "medium", "high", "critical"],
  category: ["app_shahid", "wix_raj", "content", "outreach_shakil", "pm_myren", "approval_geronimo", "hubspot", "google_sheets", "qa"],
  deal_type: ["community_pass", "swoop", "superswoop", "founding_partner_offer", "general_discount", "event_offer"],
  heha_swipe_status: ["hidden", "draft", "needs_update", "ready", "live", "paused", "error_broken_link", "not_applicable"],
  heha_local_status: ["hidden", "draft", "needs_update", "ready", "live", "paused", "error_broken_link", "not_applicable"],
  wix_status: ["hidden", "draft", "needs_update", "ready", "live", "paused", "error_broken_link", "not_applicable"],
  hubspot_status: ["hidden", "draft", "needs_update", "ready", "live", "paused", "error_broken_link", "not_applicable"],
};
