-- Preserve the existing RLS/security behavior after appending the categories column.
create or replace view public.public_swipe_partners with (security_invoker = true) as
select
  id,
  created_at,
  updated_at,
  owner_id,
  name,
  category,
  location,
  contact,
  instagram,
  website,
  bio,
  tags,
  rating,
  review_count,
  distance_text,
  color,
  photo_emoji,
  heha_partner,
  status,
  complete_pct,
  contribution,
  total_swipes,
  total_saves,
  total_profile_views,
  hours,
  google_place_id,
  business_type,
  offerings,
  neighborhood,
  tagline,
  items,
  phone,
  image_url,
  price_range,
  gallery_urls,
  partner_type,
  product_price_policy,
  service_fee_type,
  service_fee_amount,
  delivery_days,
  pricing_notes,
  heha_pillar,
  website_eligible,
  swipe_eligible,
  local_eligible,
  local_lane,
  primary_cta_destination,
  primary_cta_label,
  primary_cta_path,
  routing_status,
  routing_notes,
  routing_updated_by,
  routing_updated_at,
  is_test_record,
  categories
from public.partners
where status = any (array['approved'::text, 'live'::text])
  and coalesce(swipe_eligible, false) = true
  and is_test_record = false;

revoke all on public.public_swipe_partners from anon, authenticated;
grant select on public.public_swipe_partners to anon, authenticated;
