create table if not exists public.scout_leads (
  id uuid primary key default gen_random_uuid(),
  business_name text,
  lead_type text not null default 'potential_partner',
  pipeline_status text not null default 'new_visit',
  heha_pillar text,
  business_category text,
  neighborhood text,
  tagline text,
  bio text,
  hours text,
  address text,
  city text,
  state text,
  postal_code text,
  phone text,
  email text,
  website text,
  instagram text,
  google_maps_url text,
  primary_contact_name text,
  primary_contact_role text,
  visit_notes text,
  first_impression text,
  heha_fit_notes text,
  fit_score smallint,
  products_services text,
  offerings_text text,
  featured_items_text text,
  potential_offer text,
  image_url text,
  logo_url text,
  photo_emoji text,
  card_color text,
  gallery_urls jsonb not null default '[]'::jsonb,
  event_capacity text,
  indoor_outdoor text,
  parking_notes text,
  food_vendor_policy text,
  alcohol_policy text,
  music_noise_policy text,
  power_notes text,
  restroom_notes text,
  rental_cost_notes text,
  availability_notes text,
  source text not null default 'field_visit',
  source_detail text,
  partner_id uuid references public.partners(id) on delete set null,
  event_application_id uuid references public.event_applications(id) on delete set null,
  pm_task_id uuid references public.admin_pm_tasks(id) on delete set null,
  hubspot_status text not null default 'queued',
  hubspot_last_error text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists scout_leads_status_idx on public.scout_leads (pipeline_status, created_at desc);
create index if not exists scout_leads_type_idx on public.scout_leads (lead_type, created_at desc);
create index if not exists scout_leads_partner_idx on public.scout_leads (partner_id);

alter table public.scout_leads enable row level security;
